### ISSUE TITLE
../src/clients/query.hpp:184:3: error: ‘span’ does not name a type

### ISSUE THREAD

**Issue by feiYang560** [named-data/ndns#2]
Hi,I can't compile this project ,it report "../src/clients/query.hpp:184:3: error: ‘span’ does not name a type" when I run ./waf。I'm a little confused about what ‘span’ means

**Comment by cawka** [comment]
You need to use the released (or master branch) of ndn-cxx.  The code has been recently modernized to include new features in the library (backported from c++17)
